import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const clashGrotesk = localFont({
  variable: "--clash-grotesk-font",
  display: "swap",
  src: [
    {
      path: "fonts/ClashGrotesk-Variable.ttf",
      weight: "variable",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clashGrotesk.className}>{children}</body>
    </html>
  );
}
